[nrf fromlist] tests: drivers: watchdog: disable DCACHE for nRF54H20dk
NordicPlayground/fw-nrfconnect-zephyr pull request #2279
Opened 2024-11-19 13:46 UTC by mstasiaknordic

Disabled data caching for nRF54H20dk in wdt_basic_api test. It caused variables stored in noinit section to be cached, resulting in reset loop.

Upstream PR #: 81438

2024-11-19 14:09 UTC, nordic-segl requested changes
Don't extend sample.yaml as test `drivers.watchdog` is keep failing for nrf54h20.
Add ./boards/nrf54h20dk_nrf54h20_cpuapp.conf with
CONFIG_DCAHE=n
in it.

2024-11-20 07:05 UTC, nordic-segl approved these changes

2024-11-20 13:09 UTC, nika-nordic approved these changes

2024-11-20 13:09 UTC, kl-cruz approved these changes

2024-11-20 13:39 UTC, merged